import React, { useState } from 'react';
import './App.css';

function App() {
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState('');

  const sendMessage = () => {
    if (input.trim() === '') return;

    const userMessage = { text: input, sender: 'user' };
    setMessages([...messages, userMessage]);

    const botMessage = { text: getBotResponse(input), sender: 'bot' };
    setTimeout(() => {
      setMessages(prevMessages => [...prevMessages, botMessage]);
    }, 500);

    setInput('');
  };

  const getBotResponse = (input) => {
    const responses = {
      const responses = {
    "hello": "Hi! How can I help with your travel?",
    "hi": "Hello! What type of travel do you need?",
    "bus": "Tell me your current place and where you want to go.",
    "train": "Where are you now, and where do you want to go by train?",
    "aero plane": "Tell me where you are and your destination for a flight.",
    "aeroplane": "Please enter your current place and where you are flying to.",
    "plane": "What's your starting place and where are you going?",
    "flight": "Tell me your current place and where you want to fly.",
    "how are you": "I'm a bot, but I'm doing great!",
    "what is your name": "I'm your travel assistant!",
    "bye": "Goodbye! Have a nice trip!",
    "chennai": "Okay, let me find some options for Chennai.",
    "avs": "He’s a legend! and aunty lover",
        "avskumar": "He’s a legend! and aunty lover",
        "sanjeev": "He’s a legend! and aunty lover",
        "sanjeevkumar": "He’s a legend! and aunty lover",
    "help": "I can help you with bus, train, or flight travel.",
    "thank you": "You're welcome!",
    "what can you do": "I can help you plan your travel by bus, train, or flight.",
    "what is the best way to travel": "It depends! Buses are cheap, trains are scenic, flights are fast.",
    "how can I book a ticket": "Tell me your travel type and destination, and I'll guide you.",
    "suggest me a place to visit": "Maybe a beach or a hill station? Where do you like?",
    "I want to travel with friends": "That sounds fun! Where do you all want to go?",
    "I'm looking for budget travel": "Buses and trains are usually cheap. Where to?",
    "can I travel internationally": "Yes, flights are best for that. Where are you going?",
    "how to cancel a ticket": "Check your booking provider for cancellation rules.",
    "where can I find cheap flights": "Try booking early or use price comparison sites.",
    
    // New responses
    "what time do buses leave": "It depends on the route. Can you tell me your destination?",
    "is there a train to Delhi": "Yes, there are many trains to Delhi. When do you want to travel?",
    "what are the train timings": "Train timings vary. Please share your route.",
    "how much is a bus ticket": "Bus fares depend on the distance. Where are you going?",
    "is the flight direct": "That depends on the airline and route. Can I check for you?",
    "what's the duration of the flight": "It varies based on the destination. Which flight are you asking about?",
    "do I need to book in advance": "It's always good to book early for better prices!",
    "can I change my booking": "Yes, but it depends on the provider's policy. Can I help check?",
    "what if my flight is delayed": "Check with the airline for updates on delays.",
    "what should I pack for my trip": "It depends on where you’re going! Are you traveling to a beach or the mountains?",
    "can I travel with a pet": "It depends on the bus, train, or airline rules. Do you have a specific travel type in mind?",
    "do you have travel tips": "Always pack light, and check your itinerary before you leave!",
    "is travel insurance necessary": "It’s a good idea, especially for international trips.",
    "what is the best travel app": "Many people like using Skyscanner or Google Maps.",
    "how do I get to the airport": "You can take a taxi, bus, or train, depending on your location.",
    "what is a layover": "A layover is a break in your journey where you wait for another flight.",
    "can I book a hotel through you": "I can guide you, but you’ll need to book directly with the hotel.",
    "what is a connecting flight": "It's when you change planes during your journey.",
    "can I use public transport in the city": "Yes! Public transport is usually a great way to get around.",
    "where can I find local food": "Ask locals or use travel apps to find the best spots!",
    "how to reach the train station": "It depends on your location. Do you need directions?",
    "what is the best time to visit": "It varies by destination. Where are you planning to go?",
    "what currency do I need": "It depends on the country. Can I help with a specific place?",
    "can I get a refund on my ticket": "Refund policies vary. Check with your provider.",
    "how do I contact customer service": "You can usually find contact details on the booking site.",
    "is there a student discount": "Many travel companies offer student discounts. Which one are you interested in?",
    "what should I do if I miss my flight": "Contact the airline as soon as possible for options.",
    "how long does the bus ride take": "It depends on the route. Can you tell me where you're going?",
    "are there luggage restrictions": "Yes, it varies by bus, train, or airline. What are you taking?",
    "how early should I arrive at the airport": "It’s best to arrive at least 2 hours before a flight.",
    "what is the baggage allowance for flights": "It varies by airline. Do you want to know about a specific one?",
    "can I check my flight status": "Yes, you can check on the airline's website.",
    "what is the fastest way to travel": "Flights are usually the fastest for long distances.",
    "do I need a visa to travel": "It depends on the country you are visiting. Can I help with details?",
    "is it safe to travel alone": "Many people travel alone. Just stay aware of your surroundings.",
    "what is the best travel season": "It varies by destination. Do you have a specific place in mind?",
    "can I take food on the bus": "Yes, usually you can bring snacks. Check with the bus company.",
    "what's the best way to learn about a new city": "Explore local guides, apps, or ask locals for tips!",
    "can I travel during COVID-19": "Yes, but check the local guidelines and restrictions first.",
    "how do I pack light": "Choose versatile clothes and limit shoes!",
    "what should I wear on a plane": "Comfortable clothes and shoes are best for long flights.",
    "how to find a travel buddy": "You can use travel forums or apps to meet others!",
    "is it okay to travel during winter": "Yes, just check the weather and pack accordingly!",
    "what is a travel itinerary": "It's a plan for your trip, listing places and activities.",
    "how can I find a cheap hotel": "Use travel websites to compare prices and find deals.",
    "what are the best travel websites": "Some popular ones are Booking.com, Expedia, and Kayak.",
    "how to avoid tourist traps": "Do some research and ask locals for recommendations.",
    "is it better to book flights or hotels separately": "It depends on your preferences and any deals available.",
    "how to deal with jet lag": "Try to adjust your sleep schedule before traveling and stay hydrated.",
    "what should I do if I lose my passport": "Report it to the local authorities and your embassy immediately.",
    "how can I keep my valuables safe while traveling": "Use a money belt or keep them in a secure place.",
    "what are the customs regulations": "Check the regulations for the country you are visiting.",
    "how to find a good travel guide": "Look for reviews online or ask for recommendations from friends.",
    "what is the best way to get around a new city": "Public transport, walking, or renting a bike are great options.",
    "how to save money while traveling": "Look for deals, use public transport, and eat like a local.",
    "is it worth it to join a travel group": "It can be helpful for meeting people and getting guided tours.",
    "what are the benefits of travel insurance": "It can cover cancellations, medical emergencies, and lost luggage.",
    "how to choose a destination": "Consider your interests, budget, and travel time.",
    "can I book a one-way ticket": "Yes, many airlines and travel services offer one-way bookings.",
    "what are the health precautions for traveling": "Check vaccinations and local health guidelines for your destination.",
    "is it better to rent a car or use public transport": "It depends on your itinerary and budget.",
    "how to prepare for a road trip": "Plan your route, pack snacks, and check your vehicle.",
    "what to do if my baggage is lost": "Report it to the airline and keep tracking your baggage status.",
    "how to find last-minute travel deals": "Check travel websites or sign up for deal alerts.",
    "can I travel with a child": "Yes, but check the specific travel rules for children.",
    "what are the advantages of booking flights early": "You can save money and get better seat options.",
    "how do I keep track of my travel plans": "Use a travel app or a simple notebook.",
    "can I use my phone abroad": "Check with your carrier about international plans.",
    "what should I do if my credit card is lost": "Report it to your bank immediately to prevent misuse.",
    "is it safe to travel to [country]": "Research recent travel advisories and local safety tips.",
    "how to find the best deals on flights": "Use comparison sites and be flexible with your dates.",
    "what should I know before traveling internationally": "Check visa requirements, health regulations, and local customs.",
    "how to book a group trip": "Contact travel agencies that specialize in group travel or plan it yourself!",
    "what is a travel voucher": "It’s a credit you can use for future travel with a specific provider.",
    "how to choose the right travel insurance": "Consider coverage, exclusions, and customer reviews.",
    "can I get a refund on my hotel booking": "It depends on the hotel's cancellation policy.",
    "what to do if my flight gets canceled": "Contact the airline for rebooking options.",
    "how do I find local attractions": "Use travel apps, blogs, or ask locals for recommendations.",
    "what is the best way to book a tour": "Research online or contact local tour operators directly.",
    "how to manage travel stress": "Stay organized, take breaks, and plan ahead!",
    "can I travel with a service animal": "Yes, but check the airline or service provider's policy.",
    "how to stay connected while traveling": "Use Wi-Fi, mobile data, or local SIM cards.",
    "what to do if I miss my train": "Contact the railway service for options to catch a later one.",
    "is it necessary to carry cash when traveling": "It can be helpful, especially in places that don't accept cards.",
    "how to find public restrooms while traveling": "Use travel apps or ask locals for nearby facilities.",
    "what should I do if I encounter problems with my accommodation": "Contact the hotel management or booking service for assistance.",
    "how to keep fit while traveling": "Plan active excursions or use hotel gyms if available.",
    "is it safe to travel during the pandemic": "Check local guidelines and travel advisories before planning.",
    "how to find a local SIM card": "Look for mobile shops or kiosks at airports or major locations.",
    "can I book a guided tour last minute": "It depends on availability. Check with local tour companies.",
    "what are the risks of solo travel": "Be aware of your surroundings and trust your instincts.",
    "how to find a travel mentor": "Look for online travel communities or local travel clubs.",
    "what's the best way to capture travel memories": "Use a journal, photos, or video blogs!",
    "how to choose between a hotel and an Airbnb": "Consider location, price, and amenities.",
    "can I get my money back for a canceled trip": "It depends on your booking terms. Check with the provider.",
    "what to do if my travel plans change": "Stay flexible and contact all necessary services for updates.",
    "how to navigate an airport": "Follow the signs and ask airport staff if you need help.",
    "what to do if I have a layover": "Check if you need to leave the terminal and explore if time allows!",
    "how to find the best local experiences": "Ask locals, read travel blogs, or use experience apps.",
    "is it safe to travel with valuables": "Keep them secure and be aware of your surroundings.",
    "what to do if I feel unsafe while traveling": "Trust your instincts and seek help from local authorities if needed.",
    "how to plan a trip on a budget": "Look for deals, travel off-peak, and plan meals wisely.",
    "can I get a group discount on travel": "Many services offer group rates. Ask when booking!",
    "what's the best way to document my travel": "Use a travel journal, blog, or social media!",
    "how to handle travel emergencies": "Stay calm, have a plan, and contact the local authorities if needed.",
    "what to do if my travel companion cancels": "Consider your options or ask others to join you!",
    "how to avoid scams while traveling": "Stay aware, research common scams, and trust your instincts.",
    "is it worth it to upgrade my flight": "Consider the price difference and benefits of extra comfort.",
    "what to do if I can't find accommodation": "Look for hotels, hostels, or short-term rentals in the area.",
    "how to keep my travel documents safe": "Use a secure bag and make digital copies of important documents.",
    "can I change my travel dates": "It depends on the provider's policies. Can I check for you?",
    "what to do if I get sick while traveling": "Seek local medical help and have travel insurance for emergencies.",
    "how to find transportation options in a new city": "Use apps, ask locals, or check online guides.",
    "is it safe to drive in [country]": "Research local driving laws and conditions before traveling.",
    "how to prepare for cultural differences": "Do some research on customs and be respectful.",
    "what should I do if I encounter a language barrier": "Learn basic phrases or use translation apps.",
    "how to stay healthy while traveling": "Stay hydrated, eat balanced meals, and exercise when possible.",
    "can I travel without a credit card": "Yes, many services accept debit cards or cash.",
    "what to do if my accommodation is not as described": "Contact the booking service for assistance.",
    "how to choose a travel backpack": "Consider size, comfort, and how you’ll use it.",
    "what are the best apps for travel planning": "Some popular ones are Google Maps, TripIt, and Airbnb.",
    "how to travel sustainably": "Use public transport, support local businesses, and minimize waste.",
    "is it okay to haggle while traveling": "It depends on the location and local customs.",
    "how to find local festivals and events": "Check community boards, local websites, or travel apps.",
    "can I use a debit card abroad": "Yes, but inform your bank and check for international fees.",
    "how to travel with dietary restrictions": "Research local food options and carry snacks if needed.",
    "what to do if I encounter rude staff": "Stay calm and report the issue to management if necessary.",
    "is it safe to travel during monsoon season": "Check weather forecasts and be prepared for delays.",
    "how to find good restaurants while traveling": "Use review apps or ask locals for recommendations.",
    "can I take a taxi from the airport": "Yes, most airports have taxi services available.",
    "how to find the best travel deals": "Use comparison sites and be flexible with your travel dates.",
    "what should I do if my flight is overbooked": "Contact the airline for rebooking options.",
    "how to pack for a beach vacation": "Swimwear, sunscreen, and light clothing are essential!",
    "what's the best way to explore a city": "Walking tours, local guides, or renting a bike can be great!",
    "how to avoid getting lost while traveling": "Use maps and ask for directions when needed.",
    "what to do if I feel overwhelmed while traveling": "Take breaks, plan downtime, and stay flexible.",
    "how to choose a travel guidebook": "Look for up-to-date information and reviews.",
    "what are the benefits of solo travel": "It allows you to explore at your own pace and meet new people!",
    "how to find family-friendly activities while traveling": "Use family travel blogs and websites for ideas.",
    "what should I do if I run out of money while traveling": "Contact your bank or use emergency funds if available.",
    "how to handle culture shock while traveling": "Stay open-minded and give yourself time to adjust.",
    "can I get a refund for my tour booking": "It depends on the tour company's policy.",
    "how to find good street food while traveling": "Ask locals for their favorite spots or look for busy stalls.",
    "is it safe to travel with kids": "Yes, many families travel together. Just plan accordingly!",
    "what should I do if I lose my wallet while traveling": "Report it to local authorities and cancel your cards.",
    "how to handle travel fatigue": "Rest, stay hydrated, and take breaks when needed.",
    "what's the best way to experience local culture": "Participate in local events, try traditional foods, and meet locals.",
    "how to find travel partners online": "Join travel forums or groups on social media.",
    "what to do if I encounter rude fellow travelers": "Stay polite and remove yourself from the situation if possible.",
    "is it okay to take photos of strangers while traveling": "Always ask for permission first to respect their privacy.",
    "how to choose a travel destination based on interests": "Consider your hobbies and what experiences you want.",
    "what to do if my travel plans are disrupted": "Stay calm and contact the necessary services for assistance.",
    "how to find a good travel agency": "Look for reviews and recommendations from friends or online.",
    "can I travel during a natural disaster": "Check safety advisories and consider rescheduling.",
    "what are the advantages of traveling during off-peak times": "Lower prices and fewer crowds!",
    "how to find local transportation options": "Use apps, ask locals, or check online guides.",
    "is it worth it to book travel packages": "It can save money and simplify planning.",
    "what to do if my luggage is damaged": "Report it to the airline and take photos as evidence.",
    "how to find a good local tour guide": "Ask for recommendations or check online reviews.",
    "is it safe to use public Wi-Fi while traveling": "Avoid sensitive transactions and use a VPN if possible.",
    "how to choose a travel insurance plan": "Compare coverage and premiums before selecting a plan.",
    "what's the best way to learn about local history": "Visit museums, take guided tours, or read local literature.",
    "can I travel if I have a medical condition": "Consult your doctor and check insurance coverage.",
    "how to find the best travel photography spots": "Research online or ask fellow travelers for their favorites.",
    "what to do if my flight is delayed": "Contact the airline for updates and consider your options.",
    "how to make friends while traveling": "Join group tours or attend local events to meet people.",
    "is it okay to bring food on a flight": "Check the airline's policy for restrictions.",
    "how to travel with a large group": "Plan ahead and coordinate activities to keep everyone engaged.",
    "what to do if my credit card is lost while traveling": "Report it immediately to the bank and monitor your accounts.",
    "how to navigate through train stations": "Follow the signs and ask staff for assistance if needed.",
    "what's the best way to travel with a baby": "Bring necessary supplies and consider the baby's routine.",
    "how to manage travel anxiety": "Practice relaxation techniques and plan your itinerary in advance.",
    "can I travel with my pet": "Yes, many airlines allow pets. Check their policies.",
    "how to choose the right travel camera": "Consider size, quality, and features based on your needs.",
    "what should I do if I encounter bad weather while traveling": "Stay informed and be prepared to adjust your plans.",
    "how to find local transportation services": "Ask locals, check online, or use travel apps.",
    "is it safe to go hiking while traveling": "Research trails, take safety precautions, and inform someone of your plans.",
    "how to plan a last-minute trip": "Look for deals and be flexible with your destination and dates.",
    "what to do if my travel plans change last minute": "Stay flexible and contact all necessary services.",
    "how to find a good travel deal": "Use comparison websites and sign up for alerts.",
    "is it worth it to book a hotel with amenities": "Consider your needs and how you'll use them.",
    "what should I do if I get lost while traveling": "Stay calm, ask for help, and use maps or GPS.",
    "how to find affordable travel options": "Look for deals, travel during off-peak times, and use budget airlines.",
    "can I travel without a passport": "Not for international travel. Check local ID requirements.",
    "how to find a travel buddy": "Join travel forums or social media groups focused on travel.",
    "what's the best way to pack for a trip": "Make a checklist and roll your clothes to save space.",
    "how to find local culture and experiences": "Explore local neighborhoods, attend festivals, and try traditional foods.",
    "is it safe to travel to [country] during the holidays": "Check local advisories and plan ahead for crowds.",
    "how to handle travel delays": "Stay informed and be flexible with your plans.",
    "what should I know about local customs before traveling": "Research local etiquette and be respectful.",
    "how to choose the best travel itinerary": "Consider your interests, time, and transportation options.",
    "what to do if I encounter a medical emergency while traveling": "Seek local medical help and contact your insurance provider.",
    "can I book a last-minute flight deal": "Yes, use comparison websites to find options.",
    "how to travel with a toddler": "Bring snacks, toys, and plan for breaks.",
    "what's the best way to find travel reviews": "Check websites like TripAdvisor or travel blogs.",
    "how to handle lost luggage while traveling": "Report it to the airline and keep a record of your claims.",
    "is it safe to travel alone as a woman": "Stay aware of your surroundings and trust your instincts.",
    "how to find affordable accommodation options": "Use comparison sites and look for discounts.",
    "what should I do if I have a travel emergency": "Stay calm and contact local authorities or your embassy.",
    "how to find local dining options": "Use restaurant review apps or ask locals for recommendations.",
    "can I travel with a large pet": "Check with airlines for their pet policies.",
    "how to find good local markets while traveling": "Ask locals for their favorites or explore neighborhoods.",
    "what should I do if my travel partner has different interests": "Communicate and compromise on activities.",
    "how to plan a surprise trip for someone": "Consider their interests and involve them in the planning process.",
    "is it safe to travel in [country] with children": "Research local safety and amenities for families.",
    "how to find the best local cuisine": "Ask locals for their favorites or research online.",
    "what to do if my travel plans involve multiple destinations": "Plan your itinerary and consider transportation options.",
    "how to handle being homesick while traveling": "Stay connected with loved ones and take breaks.",
    "can I travel to [country] during the off-season": "Yes, off-peak times can offer better deals and fewer crowds.",
    "how to find good local transportation options": "Ask locals or use travel apps for recommendations.",
    "is it worth it to upgrade my hotel room": "Consider the price difference and the amenities offered.",
    "what should I do if I experience culture shock": "Give yourself time to adjust and stay open-minded.",
    "how to find local cultural experiences while traveling": "Attend local events, visit museums, and engage with locals.",
    "can I travel with a service animal in public transport": "Yes, but check local transport regulations.",
    "how to plan a road trip": "Map your route, plan stops, and ensure your vehicle is ready.",
    "what to do if my luggage is delayed": "Contact the airline and keep receipts for expenses.",
    "how to stay safe while exploring a new city": "Stay aware of your surroundings and avoid risky areas.",
    "is it safe to use my phone while traveling": "Be cautious of scams and keep your phone secure.",
    "how to find family-friendly hotels": "Use family travel websites and check reviews.",
    "what should I do if my travel plans change due to weather": "Stay flexible and monitor weather updates.",
    "how to navigate local customs while traveling": "Research and be respectful of local traditions.",
    "can I travel with my medication": "Yes, but check regulations and carry a prescription if needed.",
    "how to find local art and music events": "Check community boards and local websites for listings.",
    "is it safe to travel by public transport in [country]": "Research local transport safety and regulations.",
    "how to find good local coffee shops while traveling": "Ask locals or use review apps.",
    "what's the best way to enjoy nature while traveling": "Explore parks, go hiking, or take nature tours.",
    "how to plan a trip with a tight budget": "Look for deals, prioritize free activities, and cook meals.",
    "what to do if I experience travel burnout": "Take breaks, rest, and consider altering your plans.",
    "how to find good travel bloggers to follow": "Search online or check social media platforms.",
    "is it worth it to buy a travel guidebook": "It can be helpful for detailed information and insights.",
    "how to find local wellness retreats while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my children for free": "Many airlines offer discounts or free travel for young children.",
    "how to find the best beach destinations": "Research online and check travel blogs for recommendations.",
    "what should I do if I encounter wildlife while traveling": "Observe from a safe distance and follow local guidelines.",
    "how to plan a trip to multiple cities": "Consider transportation options and plan your itinerary.",
    "is it safe to travel to rural areas in [country]": "Research local safety and be cautious.",
    "how to find local outdoor activities while traveling": "Ask locals or check travel apps for ideas.",
    "can I travel to [country] without a visa": "Check visa requirements for your nationality.",
    "what's the best way to save on travel expenses": "Look for deals, travel off-peak, and budget carefully.",
    "how to find local volunteer opportunities while traveling": "Check community boards and local organizations.",
    "what should I do if my travel companion has dietary restrictions": "Plan meals accordingly and research local options.",
    "how to handle language barriers while traveling": "Learn key phrases and use translation apps for help.",
    "is it safe to travel during civil unrest": "Check local advisories and reconsider your plans if necessary.",
    "how to find local sports events while traveling": "Check community boards or local websites for listings.",
    "can I travel with a carry-on only": "Yes, many travelers do! Just pack wisely.",
    "how to find good local hiking trails": "Ask locals or use hiking apps for recommendations.",
    "what should I do if I encounter a language barrier while traveling": "Use translation apps or learn a few key phrases.",
    "how to plan a trip with teenagers": "Involve them in the planning process and consider their interests.",
    "is it worth it to join a travel rewards program": "It can be beneficial if you travel frequently.",
    "how to find affordable dining options while traveling": "Use restaurant review apps and look for local favorites.",
    "what should I do if I encounter a travel scam": "Stay calm, report it to local authorities, and seek help if needed.",
    "how to navigate foreign currency while traveling": "Use currency exchange services and check rates.",
    "can I travel with a service dog": "Yes, service dogs are generally allowed, but check regulations.",
    "how to find local shopping experiences while traveling": "Ask locals for recommendations or explore neighborhoods.",
    "what should I do if I encounter a travel emergency abroad": "Contact your embassy and local authorities for assistance.",
    "how to find good local festivals while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to [country] alone": "Research local safety and trust your instincts.",
    "how to find local cultural festivals while traveling": "Check community calendars and local websites for events.",
    "what's the best way to avoid tourist traps": "Research destinations and ask locals for recommendations.",
    "how to handle unexpected expenses while traveling": "Budget for extras and keep track of your spending.",
    "can I travel with a large suitcase": "Yes, but check airline restrictions for size and weight.",
    "how to find local outdoor markets while traveling": "Ask locals for recommendations or explore neighborhoods.",
    "what should I do if I lose my wallet while traveling": "Report it to local authorities and your bank immediately.",
    "how to find local educational experiences while traveling": "Visit museums, take classes, or join local tours.",
    "is it safe to travel during a pandemic": "Check local health advisories and guidelines.",
    "how to plan a multi-country trip": "Research visa requirements and transportation options.",
    "what's the best way to stay connected while traveling": "Use local SIM cards or international data plans.",
    "how to find good local souvenirs while traveling": "Ask locals or check local shops for unique items.",
    "can I travel with my own food": "Yes, but check airline restrictions for carry-on items.",
    "how to find local cooking classes while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I encounter a rude local while traveling": "Stay polite and remove yourself from the situation if needed.",
    "how to find local wellness options while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to [country] during the winter": "Research local conditions and plan accordingly.",
    "how to find good local wine and beer experiences": "Ask locals or research online for recommendations.",
    "what should I do if I experience jet lag": "Rest, stay hydrated, and adjust to the local time.",
    "how to navigate travel insurance options": "Research different plans and compare coverage.",
    "can I travel with my own water bottle": "Yes, many travelers do! Check airline restrictions.",
    "how to find local pet-friendly accommodations while traveling": "Use pet-friendly travel sites and ask locals for recommendations.",
    "what's the best way to avoid travel stress": "Plan ahead, stay organized, and take breaks.",
    "how to find local adventure activities while traveling": "Ask locals or use travel apps for ideas.",
    "can I travel during my pregnancy": "Consult your doctor and check airline policies.",
    "how to find local guided tours while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I have dietary restrictions while traveling": "Research local options and communicate your needs.",
    "how to find local craft markets while traveling": "Ask locals or use travel apps for ideas.",
    "is it safe to travel to remote areas in [country]": "Research local safety and be cautious.",
    "how to find local fitness opportunities while traveling": "Research gyms, classes, or outdoor activities.",
    "what's the best way to stay healthy while traveling": "Stay active, eat well, and stay hydrated.",
    "how to navigate travel scams": "Stay informed and trust your instincts.",
    "can I travel with a baby stroller": "Yes, but check airline policies for size and restrictions.",
    "how to find local cultural immersion experiences while traveling": "Participate in local events and engage with communities.",
    "what should I do if I lose my phone while traveling": "Report it to local authorities and your service provider.",
    "how to find local nature experiences while traveling": "Research parks, trails, and natural attractions.",
    "is it safe to travel to tourist hotspots in [country]": "Research local safety and be cautious.",
    "how to find good local art experiences while traveling": "Visit galleries, art fairs, and ask locals for recommendations.",
    "what should I do if I have a food allergy while traveling": "Communicate your allergy and research local options.",
    "how to find local historical landmarks while traveling": "Research online or ask locals for recommendations.",
    "can I travel with a medical device": "Yes, but check airline regulations for restrictions.",
    "how to find local spiritual experiences while traveling": "Visit places of worship or attend local events.",
    "what's the best way to navigate a foreign city": "Use maps, public transport, and ask locals for directions.",
    "how to find local cultural activities while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to [country] during the summer": "Research local conditions and plan accordingly.",
    "how to find good local outdoor experiences while traveling": "Ask locals or use travel apps for ideas.",
    "what should I do if I encounter wildlife on a hike while traveling": "Observe from a distance and follow local guidelines.",
    "how to navigate public transport while traveling": "Research routes, schedules, and use maps or apps.",
    "can I travel with a large musical instrument": "Check airline policies for size and restrictions.",
    "how to find local volunteer opportunities for environmental conservation while traveling": "Research local organizations and community projects.",
    "what's the best way to enjoy local cuisine while traveling": "Try street food, dine at local restaurants, and attend cooking classes.",
    "how to find local outdoor festivals while traveling": "Check community calendars and local websites for events.",
    "is it safe to travel during the holiday season": "Research local safety and plan ahead for crowds.",
    "how to find local guided nature tours while traveling": "Ask locals or use travel apps for ideas.",
    "what should I do if I encounter a natural disaster while traveling": "Stay calm, follow local advice, and seek safety.",
    "how to find local charity organizations while traveling": "Research online or ask locals for recommendations.",
    "can I travel with a bicycle": "Yes, but check airline policies for size and restrictions.",
    "how to find local cultural heritage sites while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to travel sustainably": "Use public transport, minimize waste, and support local businesses.",
    "how to find local adventure sports while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to [country] during the rainy season": "Research local conditions and plan accordingly.",
    "how to find local art galleries while traveling": "Ask locals or research online for recommendations.",
    "what should I do if I encounter a travel-related health issue": "Seek medical help and contact your insurance provider.",
    "how to find local history tours while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own surfboard": "Check airline policies for size and restrictions.",
    "how to find local wildlife tours while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to explore a new city": "Walk, use public transport, and get lost in the neighborhoods.",
    "how to find local environmental initiatives while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel during peak tourist season": "Research local safety and be prepared for crowds.",
    "how to find local music experiences while traveling": "Ask locals or check online for recommendations.",
    "what should I do if I encounter a travel-related injury": "Seek medical help and contact your insurance provider.",
    "how to find local photography spots while traveling": "Ask locals or check online for recommendations.",
    "can I travel with my own camping gear": "Check airline policies for size and restrictions.",
    "how to find local festivals celebrating food while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to interact with locals while traveling": "Be respectful, curious, and open to new experiences.",
    "how to find local historical experiences while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel during a national holiday": "Research local safety and be aware of local customs.",
    "how to find local outdoor adventure companies while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I encounter travel-related harassment": "Stay calm, seek help from authorities, and document the incident.",
    "how to find local festivals celebrating art while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own pet carrier": "Yes, but check airline policies for size and restrictions.",
    "how to find local hiking experiences while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to communicate with locals while traveling": "Learn a few key phrases and be friendly.",
    "how to find local wildlife experiences while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel during a cultural festival": "Research local safety and be aware of crowds.",
    "how to find local food festivals while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I encounter a rude traveler while traveling": "Stay polite and remove yourself from the situation if needed.",
    "how to find local fitness classes while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own kayak": "Check airline policies for size and restrictions.",
    "how to find local street food while traveling": "Ask locals or explore neighborhoods.",
    "what's the best way to embrace local customs while traveling": "Research and be respectful of local traditions.",
    "how to find local nature trails while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to remote islands": "Research local safety and be cautious.",
    "how to find local cultural exchanges while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I encounter a travel-related emotional issue": "Seek support from a professional and communicate with your support network.",
    "how to find local wellness retreats while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own fishing gear": "Check airline policies for size and restrictions.",
    "how to find local volunteer opportunities while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to enjoy nature while traveling": "Spend time outdoors, explore parks, and take guided nature tours.",
    "how to find local culinary classes while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to popular tourist attractions in [country]": "Research local safety and be cautious.",
    "how to find local historical reenactments while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I have a travel-related anxiety attack": "Find a quiet space, practice deep breathing, and seek support if needed.",
    "how to find local wildlife sanctuaries while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own golf clubs": "Check airline policies for size and restrictions.",
    "how to find local music festivals while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to enjoy local traditions while traveling": "Participate in local events and engage with communities.",
    "how to find local meditation retreats while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to cities known for nightlife": "Research local safety and be cautious.",
    "how to find local charity events while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience culture shock while traveling": "Take time to adjust, stay open-minded, and seek support.",
    "how to find local wildlife photography opportunities while traveling": "Ask locals or check online for recommendations.",
    "can I travel with my own yoga mat": "Check airline policies for size and restrictions.",
    "how to find local boat tours while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to meet new people while traveling": "Stay in hostels, join tours, and participate in local events.",
    "how to find local art classes while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to areas with high crime rates": "Research local safety and avoid risky areas.",
    "how to find local storytelling events while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I encounter travel-related depression": "Seek support from a mental health professional and communicate with your support network.",
    "how to find local cultural workshops while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own roller skates": "Check airline policies for size and restrictions.",
    "how to find local photography workshops while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to learn a new language while traveling": "Practice speaking, take classes, and immerse yourself in the culture.",
    "how to find local dance classes while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to rural areas in [country]": "Research local safety and be cautious.",
    "how to find local knitting or crafting groups while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I have a travel-related panic attack": "Find a quiet space, practice deep breathing, and seek support if needed.",
    "how to find local community events while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own skates": "Check airline policies for size and restrictions.",
    "how to find local pottery or art studios while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to engage with the local community while traveling": "Participate in events and volunteer opportunities.",
    "how to find local adult education classes while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to areas with political unrest": "Research local safety and stay informed.",
    "how to find local farmer's markets while traveling": "Ask locals or research online for recommendations.",
    "what should I do if I experience travel-related loneliness": "Reach out to friends and family, join groups, and participate in activities.",
    "how to find local beach clean-up opportunities while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own metal detector": "Check airline policies for size and restrictions.",
    "how to find local cultural performances while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to maintain a healthy routine while traveling": "Exercise regularly, eat well, and prioritize sleep.",
    "how to find local adventure groups while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to countries with travel advisories": "Research local safety and stay informed.",
    "how to find local spiritual retreats while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I encounter a language barrier while traveling": "Use translation apps and be patient.",
    "how to find local cooking demonstrations while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own surf gear": "Check airline policies for size and restrictions.",
    "how to find local volunteer opportunities for education while traveling": "Research local organizations and community projects.",
    "what's the best way to enjoy local nightlife while traveling": "Ask locals for recommendations and be aware of safety.",
    "how to find local craft fairs while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to countries with health risks": "Research local health advisories and stay informed.",
    "how to find local historical societies while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related confusion": "Stay calm, seek help from locals, and communicate clearly.",
    "how to find local environmental education programs while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own sporting equipment": "Check airline policies for size and restrictions.",
    "how to find local cultural heritage programs while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to celebrate local holidays while traveling": "Participate in local events and traditions.",
    "how to find local technology workshops while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to countries with travel bans": "Research local regulations and stay informed.",
    "how to find local book clubs while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related anger": "Stay calm, practice deep breathing, and seek support if needed.",
    "how to find local cultural exchange programs while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own art supplies": "Check airline policies for size and restrictions.",
    "how to find local music or theater productions while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to appreciate local culture while traveling": "Engage with locals and participate in traditions.",
    "how to find local gardening groups while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to countries with high poverty rates": "Research local safety and be cautious.",
    "how to find local film festivals while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related sadness": "Reach out to friends and family, and seek support if needed.",
    "how to find local conservation projects while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own sports uniform": "Check airline policies for size and restrictions.",
    "how to find local historical sites while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to learn about local customs while traveling": "Research and engage with locals.",
    "how to find local photography exhibitions while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to areas with political protests": "Research local safety and avoid protest zones.",
    "how to find local fitness retreats while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I encounter a travel-related challenge": "Stay calm, seek help, and adapt to the situation.",
    "how to find local makerspaces while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own camping stove": "Check airline policies for size and restrictions.",
    "how to find local historical reenactments while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to give back to the local community while traveling": "Participate in volunteer opportunities and support local businesses.",
    "how to find local technology meetups while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to countries with unstable governments": "Research local safety and stay informed.",
    "how to find local sports events while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related frustration": "Practice deep breathing, take a break, and seek support if needed.",
    "how to find local painting workshops while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own photography equipment": "Check airline policies for size and restrictions.",
    "how to find local poetry readings while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to interact with locals while traveling": "Be friendly, respectful, and open-minded.",
    "how to find local sewing groups while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to areas with natural disasters": "Research local safety and stay informed.",
    "how to find local food tours while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related disappointment": "Stay positive, seek support, and adapt to the situation.",
    "how to find local outdoor adventure companies while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own musical instruments": "Check airline policies for size and restrictions.",
    "how to find local social clubs while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to document my travels while traveling": "Take photos, keep a journal, and share experiences.",
    "how to find local charity organizations while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to countries with poor healthcare": "Research local health facilities and stay informed.",
    "how to find local networking events while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I encounter travel-related fatigue": "Rest, stay hydrated, and prioritize self-care.",
    "how to find local craft breweries while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own bicycle": "Check airline policies for size and restrictions.",
    "how to find local creative writing workshops while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to explore local art scenes while traveling": "Visit galleries, attend events, and engage with artists.",
    "how to find local history tours while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to countries with travel restrictions": "Research local regulations and stay informed.",
    "how to find local bookshops while traveling": "Ask locals or research online for recommendations.",
    "what should I do if I encounter travel-related stress": "Practice relaxation techniques and seek support if needed.",
    "how to find local co-working spaces while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own fishing rods": "Check airline policies for size and restrictions.",
    "how to find local cultural institutions while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to experience local cuisine while traveling": "Try local dishes and visit local eateries.",
    "how to find local environmental organizations while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to areas affected by environmental issues": "Research local safety and be cautious.",
    "how to find local cycling groups while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related regret": "Reflect on experiences, learn from them, and seek support if needed.",
    "how to find local art festivals while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own mountain bike": "Check airline policies for size and restrictions.",
    "how to find local community organizations while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to find travel companions while traveling": "Join travel groups or forums, and connect with fellow travelers.",
    "how to find local cultural exchanges while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to countries with travel advisories": "Research local safety and stay informed.",
    "how to find local educational workshops while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related disappointment": "Stay positive, adapt to the situation, and seek support.",
    "how to find local improv classes while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own sports gear": "Check airline policies for size and restrictions.",
    "how to find local historical markers while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to make the most of my travel experience": "Stay open-minded, try new things, and engage with locals.",
    "how to find local theater companies while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to areas with civil unrest": "Research local safety and avoid protest zones.",
    "how to find local outdoor markets while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I encounter travel-related frustration": "Take a break, practice self-care, and seek support if needed.",
    "how to find local cultural festivals while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own kite": "Check airline policies for size and restrictions.",
    "how to find local artist collectives while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to stay safe while traveling alone": "Stay aware of surroundings, trust instincts, and have a plan.",
    "how to find local historical re-enactments while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to areas with health risks": "Research local health advisories and stay informed.",
    "how to find local street fairs while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related homesickness": "Stay connected with loved ones, and engage in activities that bring joy.",
    "how to find local sustainability initiatives while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own camping gear": "Check airline policies for size and restrictions.",
    "how to find local hiking trails while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to enjoy local traditions while traveling": "Participate in local events and be respectful.",
    "how to find local health and wellness programs while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to areas with natural disasters": "Research local safety and stay informed.",
    "how to find local volunteer opportunities for conservation while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related isolation": "Reach out to friends and family, and join group activities.",
    "how to find local cooking schools while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own sports equipment": "Check airline policies for size and restrictions.",
    "how to find local history museums while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to learn about local history while traveling": "Visit museums, engage with locals, and read local literature.",
    "how to find local theater festivals while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to countries with political instability": "Research local safety and stay informed.",
    "how to find local farmers' markets while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related stress": "Practice relaxation techniques and seek support if needed.",
    "how to find local health clinics while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own musical instruments": "Check airline policies for size and restrictions.",
    "how to find local art galleries while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to engage with the local community while traveling": "Participate in events and volunteer opportunities.",
    "how to find local history lectures while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to countries with poor infrastructure": "Research local safety and stay informed.",
    "how to find local farmers' markets while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related guilt": "Reflect on experiences, learn from them, and seek support if needed.",
    "how to find local cooking classes while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own surfboard": "Check airline policies for size and restrictions.",
    "how to find local art exhibitions while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to appreciate local culture while traveling": "Engage with locals, attend events, and try local foods.",
    "how to find local wildlife conservation programs while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to areas with political turmoil": "Research local safety and stay informed.",
    "how to find local street performers while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related confusion": "Stay calm, ask locals for help, and adapt as needed.",
    "how to find local sustainable tourism programs while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own water sports equipment": "Check airline policies for size and restrictions.",
    "how to find local historical societies while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to support local economies while traveling": "Shop local, eat at local restaurants, and support local businesses.",
    "how to find local literary events while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to areas with crime": "Research local safety and stay informed.",
    "how to find local festivals while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related overwhelm": "Take a break, prioritize self-care, and seek support if needed.",
    "how to find local cultural institutions while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own ski equipment": "Check airline policies for size and restrictions.",
    "how to find local fitness classes while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to navigate local customs while traveling": "Research customs beforehand and ask locals for guidance.",
    "how to find local art installations while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to areas with health risks": "Research local health advisories and stay informed.",
    "how to find local nature reserves while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I encounter travel-related frustration": "Take a break, practice self-care, and seek support if needed.",
    "how to find local environmental initiatives while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own diving equipment": "Check airline policies for size and restrictions.",
    "how to find local art walks while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to learn a few local phrases while traveling": "Practice common phrases and engage with locals.",
    "how to find local photography exhibitions while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to countries with low safety ratings": "Research local safety and stay informed.",
    "how to find local film screenings while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related anger": "Practice relaxation techniques and seek support if needed.",
    "how to find local community projects while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own art supplies": "Check airline policies for size and restrictions.",
    "how to find local wildlife tours while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to share my travel experiences while traveling": "Document experiences and share on social media or blogs.",
    "how to find local guided tours while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to countries with political issues": "Research local safety and stay informed.",
    "how to find local food festivals while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related disillusionment": "Reflect on experiences, learn from them, and seek support if needed.",
    "how to find local workshops while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own rollerblades": "Check airline policies for size and restrictions.",
    "how to find local poetry slams while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to engage with local traditions while traveling": "Participate in local events and be respectful.",
    "how to find local community service projects while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to countries with high crime rates": "Research local safety and stay informed.",
    "how to find local art fairs while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related anxiety": "Practice relaxation techniques and seek support if needed.",
    "how to find local cultural exchange programs while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own climbing gear": "Check airline policies for size and restrictions.",
    "how to find local writing workshops while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to connect with locals while traveling": "Be friendly, respectful, and engage in conversations.",
    "how to find local film festivals while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to areas with high pollution": "Research local health advisories and stay informed.",
    "how to find local hiking groups while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I encounter travel-related jealousy": "Reflect on experiences, learn from them, and seek support if needed.",
    "how to find local outdoor festivals while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own yoga mat": "Check airline policies for size and restrictions.",
    "how to find local guided hikes while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to support local artists while traveling": "Purchase local art, attend events, and promote their work.",
    "how to find local farmers' co-ops while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to areas with civil unrest": "Research local safety and avoid protest zones.",
    "how to find local farmers' markets while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related fatigue": "Rest, stay hydrated, and prioritize self-care.",
    "how to find local cultural organizations while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own fitness equipment": "Check airline policies for size and restrictions.",
    "how to find local wellness retreats while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to experience local customs while traveling": "Be open-minded and engage with locals.",
    "how to find local environmental education programs while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to countries with travel advisories": "Research local regulations and stay informed.",
    "how to find local artisan markets while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related guilt": "Reflect on experiences, learn from them, and seek support if needed.",
    "how to find local environmental conservation projects while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own camera gear": "Check airline policies for size and restrictions.",
    "how to find local community events while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to learn about local traditions while traveling": "Engage with locals and participate in cultural events.",
    "how to find local art events while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to countries with natural disasters": "Research local safety and stay informed.",
    "how to find local street fairs while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related confusion": "Stay calm, ask locals for help, and adapt as needed.",
    "how to find local cultural festivals while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own yoga props": "Check airline policies for size and restrictions.",
    "how to find local hiking trails while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to connect with the local community while traveling": "Participate in local events and engage in conversations.",
    "how to find local creative workshops while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to countries with health risks": "Research local health advisories and stay informed.",
    "how to find local volunteer opportunities while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related sadness": "Reflect on experiences, seek support, and engage in activities that bring joy.",
    "how to find local cultural experiences while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own art supplies": "Check airline policies for size and restrictions.",
    "how to find local farmers' markets while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to engage with local traditions while traveling": "Participate in local events and be respectful.",
    "how to find local community service projects while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to countries with high crime rates": "Research local safety and stay informed.",
    "how to find local art fairs while traveling": "Research online or ask locals for recommendations.",
    "what should I do if I experience travel-related anxiety": "Practice relaxation techniques and seek support if needed.",
    "how to find local cultural exchange programs while traveling": "Research online or ask locals for recommendations.",
    "can I travel with my own climbing gear": "Check airline policies for size and restrictions.",
    "how to find local writing workshops while traveling": "Research online or ask locals for recommendations.",
    "what's the best way to connect with locals while traveling": "Be friendly, respectful, and engage in conversations.",
    "how to find local film festivals while traveling": "Research online or ask locals for recommendations.",
    "is it safe to travel to areas with high pollution": "Research local health advisories and stay informed.",
    "how to find local hiking groups while traveling": "Research online or ask locals for recommendations."



    };

    input = input.toLowerCase();
    return responses[input] || "this chatbot for your travel queries only ,please ask related to travel and tourism ";
  };

  return (
    <div className="chatbot">
      <div className="chatbot-messages">
        {messages.map((message, index) => (
          <div key={index} className={`message ${message.sender}-message`}>
            {message.text}
          </div>
        ))}
      </div>
      <div className="chatbot-input">
        <input 
          type="text" 
          value={input} 
          onChange={(e) => setInput(e.target.value)} 
          onKeyPress={(e) => e.key === 'Enter' && sendMessage()} 
          placeholder="Type here for your travels!..........." 
        />
        <button onClick={sendMessage}>Send</button>
      </div>
    </div>
  );
}

export default App;
